[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# SPA routing - все запросы перенаправляем на index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройки для функций
[build.environment]
  NODE_VERSION = "18"
